In [1]:
!python helpers/process_survey.py

In [2]:
import pandas as pd 

df = pd.read_csv("survey_cleaned.csv")

In [3]:
df.head()

         File  AudioID  Emotion Intensity  Gender
0  audio1.wav        1    Angry    Strong    Male
1  audio2.wav        2     Calm    Normal    Male
2  audio3.wav        3  Disgust    Normal  Female
3  audio4.wav        4    Happy    Strong  Female
4  audio5.wav        5     Calm    Normal  Female

In [4]:
pd.crosstab(df["AudioID"],[df["Emotion"],df["Intensity"]])

Emotion    Angry   Calm        Disgust        Fearful  Happy    Sad         \
Intensity Strong Normal Strong  Normal Strong  Normal Strong Normal Strong
AudioID
1             16      0      0       0      1       0      0      0      0
2              0     13      1       0      0       0      0      3      0
3              0      4      0       4      3       2      1      0      1
4              0      0      0       0      0       0     14      1      0
5              0      8      0       0      0       0      0      6      3

Emotion   Surprised
Intensity    Normal Strong
AudioID
1                 0      0
2                 0      0
3                 2      0
4                 0      2
5                 0      0

In [5]:
def get_mode(series):
    return series.mode().iloc[0] if not series.mode().empty else None

mode_df = df.groupby('AudioID')[['Emotion', 'Intensity', 'Gender']].agg(get_mode).reset_index()

count_series = []

for col in ['Emotion', 'Intensity', 'Gender']:
    merged = df.merge(mode_df[['AudioID', col]], on='AudioID', suffixes=('', '_mode'))
    count_col = merged.groupby('AudioID').apply(
        lambda x: (x[col] == x[f'{col}_mode']).sum()
    ).rename(f'{col}_count')
    count_series.append(count_col)

counts_df = pd.concat(count_series, axis=1).reset_index()

counts_df = pd.concat(count_series, axis=1).reset_index()
result_df = mode_df.merge(counts_df, on='AudioID')

In [6]:
result_df

,AudioID,Emotion,Intensity,Gender,Emotion_count,Intensity_count,Gender_count
0,1,Angry,Strong,Male,16,17,17
1,2,Calm,Normal,Male,14,16,17
2,3,Disgust,Normal,Female,7,12,16
3,4,Happy,Strong,Female,14,16,17
4,5,Sad,Normal,Female,9,14,17

In [7]:
ids = [i for i in range(1,6)]
emotions =["Angry",	"Calm",	"Disgust","Fearful","Happy","Sad","Surprised"]
intensity = ["Normal","Strong"]
Gender = ["Male","Female"]

count = {}
for id in ids:
    count[id] = {}
    for emotion in emotions:
        count[id][emotion] = {
            "Normal":{"Male":0,"Female":0}, 
            "Strong":{"Male":0,"Female":0}
            }

with open("survey_cleaned.csv") as f:
    data = f.read().splitlines()
    rows = data[1:]
    for row in rows:
        values = row.split(",")
        id = int(values[1])
        e = values[2]
        i = values[3]
        g = values[4]
        count[id][e][i][g] += 1

In [2]:
import numpy as np
np.array([])

array([], dtype=float64)